const express = require('express')
require('dotenv').config()
const cors = require('cors')
const App = express()
App.use(express.json())
const DbConnect = require('./DbConfig')
DbConnect()
// App.use(cors())
App.use(cors({ origin: ['http://localhost:5173'] }))
const guryahaRouter = require('./Router/guryahaRouter')
const Routeuser = require('./Router/userRouter')
const imagesRouter = require('./Router/imagesRouter')
const homestitingRouter = require('./Router/homestitingRouter')
const ImagegallaryRouter = require('./Router/Image_gallaryRouter')
const OutClientRouter = require('./Router/Out_ClientRouter')
const ServiceRouter = require('./Router/ServiceRouter')
const contectRouter = require('./Router/contectRouter')
const loginRouter = require('./Router/LoginRouter')
const aboutRoute=require('./Router/aboutRouter')
const {AuthernticateRoute}=require('./Router/AutherncationMiddleWare')

App.listen(5000, () => {
  console.log('server started')
})
// localhost:3000/
App.get('/', (req, res) => {
  res.json('Ku so dawaaw Serverkena')
})

App.use('/guryah',AuthernticateRoute(["Admin"]), guryahaRouter)
App.use('/users',AuthernticateRoute(["Admin"]),Routeuser)
App.use('/images',AuthernticateRoute(["Admin"]), imagesRouter)
App.use('/homestiting',AuthernticateRoute(["Admin"]), homestitingRouter)
App.use('/Image_gallary', ImagegallaryRouter)
App.use('/Out_Client',AuthernticateRoute(["Admin"]), OutClientRouter)
App.use('/Service',AuthernticateRoute(["Admin"]), ServiceRouter)
App.use('/contect',AuthernticateRoute(["Admin"]), contectRouter)
App.use('/Login', loginRouter)
App.use('/about',aboutRoute)

module.exports = App
